<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>FocusTimer</AssemblyName>
    <RootNamespace>FocusTimer</RootNamespace>
    <ApplicationIcon>app.ico</ApplicationIcon>
    <Product>Mori Timer</Product>
    <Description>简约的 Windows 倒计时与正计时工具</Description>
    <Authors>snnabb</Authors>
    <Version>2.6.0</Version>
    <AssemblyVersion>2.6.0.0</AssemblyVersion>
    <FileVersion>2.6.0.0</FileVersion>
    <InformationalVersion>2.6.0</InformationalVersion>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
  </PropertyGroup>

</Project>
